Tsk 69
software-maestro-starting-blue/daily-painting pull request #11
Opened 2024-06-22 05:50 UTC by minseojo

# [feat] 사용자 일기 폼 페이지 개발
### Pull Request 타입
- [ ] bug
- [x] feat
- [ ] style
- [ ] refactor(기능 변경 없음)
- [ ] build
- [ ] CI/CD
- [ ] doc
- [ ] chore

### TSK-
---
* 구현 내용
- 감정, 만난사람, 날씨, 한 줄 일기 컴포넌트 개발
- 완료 버튼
    - API Request

2024-06-22 06:27 UTC, JuneBridge03 requested changes
너무나 좋은 코드 감사드립니다..!

특히나 매우 많은 양의 코드를 작성하셔야 하고 다양한 컴포넌트를 하나의 pr에서 관리하시기 힘드셨을텐데 너무 수고 많으셨습니다..!

수고하신만큼 코드가 좋을 것 같습니다.!!

이에 따라 조금의 수정이 더 잇으면 좋을 듯 한 부분을 올려놓으니 확인해주시면 너무 감사드리겠습니다..!

2024-06-22 06:27 UTC, JuneBridge03 commented on frontend/src/pages/DiaryFormPage/DiaryFormPage.tsx
> +  }
if - return 문이므로 다음과 같이 수정하셔도 좋을 듯 합니다.

  if (!formData) 
    return <div>Loading...</div>;

2024-06-22 06:27 UTC, JuneBridge03 commented on frontend/src/components/Diary/BirthYearInput/BirthYearInput.tsx
> +  const handleChange = (e: ChangeEvent<HTMLSelectElement>) => {
함수명을 handleBirthYearChange 와 같이 바꾸어도 좋을 것 같습니다!

2024-06-22 06:27 UTC, JuneBridge03 commented on frontend/src/components/Diary/BirthYearInput/BirthYearInput.tsx
> +  };
차라리 BirthYearInput 컴포넌트 밖에 또 다른 하나의 컴포넌트로 분리하는 것이 더 좋을 것 같습니다..!

2024-06-22 06:27 UTC, JuneBridge03 commented on frontend/src/components/Diary/EmotionSelection/EmotionSelection.tsx
> +  handleEmotionChange: (emotion: string) => void;
handleEmotionChange라는 변수명 대신에 onEmotionClick으로 변경하는 것이 더욱 좋을 것 같습니다.

해당하는 이유로는 다음과 같습니다..!
1. props로 받을 경우에는 on~~ 과 같은 형태로 받고 이벤트를 직접 처리하는 함수일 경우에는 handle~~ 과 같이 구성하여야 코딩컨벤션이 지켜지는 것 같습니다..!
2. change라는 동사가 불명확한 느낌을 주는 듯 합니다. 특히나 이는 GenderSelection에서 정의된 handleGenderChange를 확인하였을 때, 두 역할이 다름에도 (onClick과 onChange) 하나의 동사를 사용하게 되면서 이름의 불명확성이 커지는 듯한 느낌입니다. 따라서 통일성을 위하여 조심스럽게 change로 제안드리는 바입니다.

2024-06-22 06:27 UTC, JuneBridge03 commented on frontend/src/components/Diary/MetPeopleSelection/MetPeopleSelection.tsx
> +  handleMetPeopleChange: (person: string) => void;
handleMetPeopleChange라는 변수명 대신에 onMetPeopleClick으로 변경하는 것이 더욱 좋을 것 같습니다.

해당하는 이유로는 다음과 같습니다..!

props로 받을 경우에는 on~~ 과 같은 형태로 받고 이벤트를 직접 처리하는 함수일 경우에는 handle~~ 과 같이 구성하여야 코딩컨벤션이 지켜지는 것 같습니다..!
change라는 동사가 불명확한 느낌을 주는 듯 합니다. 특히나 이는 GenderSelection에서 정의된 handleGenderChange를 확인하였을 때, 두 역할이 다름에도 (onClick과 onChange) 하나의 동사를 사용하게 되면서 이름의 불명확성이 커지는 듯한 느낌입니다. 따라서 통일성을 위하여 조심스럽게 change로 제안드리는 바입니다.

2024-06-22 06:27 UTC, JuneBridge03 commented on frontend/src/components/Diary/EmotionSelection/EmotionSelection.tsx
> +  handleEmotionChange: (emotion: string) => void;
혹은 직접 onClick을 핸들링하는 함수와의 차별점도 강조하기 위해 onEmotionSelect와 같이 변경하는 것도 괜찮은 방법일 듯 합니다..! (밑에서의 내용들에서도 동일하다고 생각합니다!)

2024-06-22 06:27 UTC, JuneBridge03 commented on frontend/src/components/Diary/WeatherSelection/WeatherSelection.tsx
> +  };
handleWeatherChange라는 변수명 대신에 handleWeatherClick으로 변경하는 것이 더욱 좋을 것 같습니다.

해당하는 이유로는 다음과 같습니다..!

change라는 동사가 불명확한 느낌을 주는 듯 합니다. 특히나 이는 GenderSelection에서 정의된 handleGenderChange를 확인하였을 때, 두 역할이 다름에도 (onClick과 onChange) 하나의 동사를 사용하게 되면서 이름의 불명확성이 커지는 듯한 느낌입니다. 따라서 통일성을 위하여 조심스럽게 change로 제안드리는 바입니다.

2024-06-22 06:27 UTC, JuneBridge03 commented on frontend/src/pages/DiaryFormPage/DiaryFormPage.tsx
> +import MetPeopleSelection from '../../components/Diary/MetPeopleSelection/MetPeopleSelection';
패키지 구조 관련하여서 두 가지를 제안드리는 바입니다..!

1. Diary 패키지명을 diaryform 으로 변경하는 것이 좋을 듯 합니다. 대소문자 통일성과 DiaryResult 컴포넌트의 폴더명(diaryresult)와의 차별성을 위해서입니다.
2. ~~Selection에서 더 나아가서 ~~SelectionLayout 과 같이 'Layout'이라는 계층을 붙이면 좋을 것 같습니다. 추후 컴포넌트 사이에서의 상하 관계를 조금 더 명확하게 하는 데 도움이 될 것 같다라는 느낌입니다.

2024-06-22 06:27 UTC, JuneBridge03 commented on frontend/src/components/Diary/EmotionSelection/EmotionSelection.tsx
> +          </div>
Emotion에 대한 각각의 컴포넌트를 분리하여도 괜찮을 것 같아 보입니다...!

2024-06-22 06:27 UTC, JuneBridge03 commented on frontend/src/components/Diary/MetPeopleSelection/MetPeopleSelection.tsx
> +          </div>
MetPeople에 대한 컴포넌트를 각각 분리하여도 좋을 것 같다는 생각이 듭니다...!

2024-06-22 06:27 UTC, JuneBridge03 commented on frontend/src/components/Diary/WeatherSelection/WeatherSelection.tsx
> +          </div>
Weather에 대한 각각의 컴포넌트를 분리하여도 좋을 것 같습니다..!

2024-06-22 06:27 UTC, JuneBridge03 commented on frontend/src/components/Diary/DiaryContent/DiaryContent.tsx
> +        onChange={(e: ChangeEvent<HTMLTextAreaElement>) => setContent(e.target.value)}
위에서 handleDiaryContentChange 함수를 지정하는 것이 더 좋을 것 같아보이면서도 아닌 것 같아보여서 판단에 맡기겠습니다..!

2024-06-22 06:51 UTC, minseojo commented on frontend/src/pages/DiaryFormPage/DiaryFormPage.tsx
> +  }
넵 참고하겠습니다. 저희만의 컨벤션을 정해봅시다!

2024-06-22 06:53 UTC, minseojo commented on frontend/src/components/Diary/BirthYearInput/BirthYearInput.tsx
> +  const handleChange = (e: ChangeEvent<HTMLSelectElement>) => {
넵 알겠습니다!

2024-06-22 06:55 UTC, minseojo commented on frontend/src/components/Diary/BirthYearInput/BirthYearInput.tsx
> +  };
넵 알겠습니다!

2024-06-22 06:56 UTC, minseojo commented on frontend/src/components/Diary/EmotionSelection/EmotionSelection.tsx
> +  handleEmotionChange: (emotion: string) => void;
넵 알겠습니다! `onEmotionClick`로 수정하겠습니다!

2024-06-22 06:57 UTC, minseojo commented on frontend/src/components/Diary/MetPeopleSelection/MetPeopleSelection.tsx
> +  handleMetPeopleChange: (person: string) => void;
넵 알겠습니다!

2024-06-22 07:02 UTC, minseojo commented on frontend/src/pages/DiaryFormPage/DiaryFormPage.tsx
> +import MetPeopleSelection from '../../components/Diary/MetPeopleSelection/MetPeopleSelection';
넵 알겠습니다!

2024-06-22 07:22 UTC, minseojo commented on frontend/src/components/Diary/EmotionSelection/EmotionSelection.tsx
> +          </div>
넵 알겠습니다!

2024-06-22 07:22 UTC, minseojo commented on frontend/src/components/Diary/DiaryContent/DiaryContent.tsx
> +        onChange={(e: ChangeEvent<HTMLTextAreaElement>) => setContent(e.target.value)}
참고해서 변경했습니다!

2024-06-22 07:46 UTC, SproutMJ approved these changes
깔끔한 코드 좋습니다~~

2024-06-23 03:17 UTC, JuneBridge03 approved these changes
수고해주셔서 감사합니다.

2024-06-23 03:24 UTC, merged