[feat][refactor] AI 서비스 테스트 코드 작성 & 리팩토링 & 예외 처리
software-maestro-starting-blue/daily-painting pull request #16
Opened 2024-06-28 08:48 UTC by JuneBridge03

# [feat][refactor] AI 서비스 테스트 코드 작성 & 리팩토링 & 예외 처리
### Pull Request 타입
- [ ] bug
- [x] feat
- [ ] style
- [x] refactor(기능 변경 없음)
- [ ] build
- [ ] CI/CD
- [ ] doc
- [ ] chore

### TSK-92, TSK-95, TSK-98
---
* 구현 내용
- 테스트 코드 작성
- 폴더 구조 리팩토링
- 예외 처리 핸들링

* 추가 발생한 문제

2024-06-29 04:02 UTC, minseojo requested changes
좋은 코드 잘 보았습니다~~
비동기 코드 부분만 변경 요청 드립니다!

2024-06-29 04:02 UTC, minseojo commented on backend/src/main/java/com/startingblue/dailypainting/ai/service/vision/Dalle3VisionService.java
> +            throw new RuntimeException("LLM responseBody Json parsing 에러", e);
RuntimeException 의 자식 또는 커스텀 예외를 만들어 구체적인 예외를 던지면 좋을 것 같습니다!

2024-06-29 04:05 UTC, JuneBridge03 commented on backend/src/main/java/com/startingblue/dailypainting/ai/exception/AIErrorResponse.java
> +public class AIErrorResponse {
네 너무 좋습니다~ 모든 PR 완료된 이후에 이에 대해 조정하면 될 것 같습니다~!

2024-06-29 04:06 UTC, JuneBridge03 commented on backend/src/main/java/com/startingblue/dailypainting/ai/service/PromptDiaryConvertService.java
>                      String.join(" ", personPrompts));
네 저도 해당 부분이 고민이기는 하였는데요.
추후에 엔티티를 만들어서 진행시킬까도 고민 요소이기는 합니다.

일단 확인했습니다~!

2024-06-29 04:07 UTC, JuneBridge03 commented on backend/src/test/java/com/startingblue/dailypainting/ai/service/scenario/ScenarioServiceTest.java
> +class ScenarioServiceTest {
넵 현 PR에서 반영해보도록 하겠습니다!

2024-06-29 04:08 UTC, JuneBridge03 commented on backend/src/main/java/com/startingblue/dailypainting/ai/service/AIDiaryService.java
>          return CompletableFuture.completedFuture(imageUrl);
아 넵 해당 방식이 더 좋은 것 같습니다.

사실 선후 관계가 거의 필수적인 요소여서 차라리 해당 함수 로직 자체를 비동기 처리로 바꾸는 것이 더 좋을 듯 하기도 합니다.

반영해보도록 하겠습니다

2024-06-29 04:08 UTC, JuneBridge03 commented on backend/src/main/java/com/startingblue/dailypainting/ai/service/vision/Dalle3VisionService.java
> +            throw new RuntimeException("LLM responseBody Json parsing 에러", e);
네 현 PR에서 한번 반영하고 커밋 링크 걸겠습니다!

2024-06-29 04:12 UTC, JuneBridge03 commented on backend/src/main/java/com/startingblue/dailypainting/ai/service/PromptDiaryConvertService.java
>                      String.join(" ", personPrompts));
생각해본 결과 현행 구조를 이어간다면 추후에 필요시 OCP 원칙에 의거하여 새로운 DiaryConvertService에 대한 구현체를 구현하는 것도 방법이 될 것 같다고 생각합니다..!

2024-06-29 05:04 UTC, JuneBridge03 commented on backend/src/main/java/com/startingblue/dailypainting/ai/service/AIDiaryService.java
>          return CompletableFuture.completedFuture(imageUrl);
6c8ae634f82b258cb8861b958010ca0977abfa40

해당 커밋에서 적용을 하기는 하였으나, 추후에 조금 더 고도화하여서 논의하면 좋을 듯 하네요~

2024-06-29 05:24 UTC, JuneBridge03 commented on backend/src/test/java/com/startingblue/dailypainting/ai/service/scenario/ScenarioServiceTest.java
> +class ScenarioServiceTest {
현 PR에서 반영해보고자 하였으나, 해당 Test 코드 작성을 위해서는 Mockito와 같은 방식이 필요할 것 같습니다. (OpenAI의 API response 자체를 조작해야 함)
 
따라서 현재 Comment는 Async 문제에 집중된 것 같아서 해당 테스트 코드는 조금 더 고심하고 추후에 적용하겠습니다.

2024-06-29 05:26 UTC, JuneBridge03 commented on backend/src/main/java/com/startingblue/dailypainting/ai/service/vision/Dalle3VisionService.java
> +            throw new RuntimeException("LLM responseBody Json parsing 에러", e);
[f0346b8](https://github.com/software-maestro-starting-blue/daily-painting/pull/16/commits/f0346b886b3a5292fd9751eab004dca6bb820a7c)

해당 Commit에서 해당 사안을 반영하기는 하였으나, AI 패키지 내 구조를 바꿀 예정인 만큼 해당 커스텀 에러 구조에 대해서도 같이 논의하면 좋을 듯 합니다.

2024-07-01 05:51 UTC, JuneBridge03 commented
> 좋은 코드 잘 보았습니다~~ 비동기 코드 부분만 변경 요청 드립니다!

반영가능한 부분 반영하였으니 확인 한 번 더 해주시면 너무 감사드립니다~

2024-07-01 06:25 UTC, minseojo commented
> > 좋은 코드 잘 보았습니다~~ 비동기 코드 부분만 변경 요청 드립니다!
> 
> 반영가능한 부분 반영하였으니 확인 한 번 더 해주시면 너무 감사드립니다~

확인했습니다~~

2024-07-01 06:25 UTC, minseojo approved these changes

2024-07-01 07:44 UTC, SproutMJ approved these changes
좋은 것 같습니다.

2024-07-03 03:03 UTC, merged