[feat] 피드백 감사 페이지 구현
software-maestro-starting-blue/daily-painting pull request #17
Opened 2024-06-28 12:05 UTC by SproutMJ

# [feat] 피드백 감사 페이지 구현
### Pull Request 타입
- [ ] bug
- [x] feat
- [ ] style
- [ ] refactor(기능 변경 없음)
- [ ] build
- [ ] CI/CD
- [ ] doc
- [ ] chore

### TSK-115
---
* 구현 내용
피드백 이후 감사(완료) 페이지 구현

* 추가 발생한 문제

2024-06-29 01:35 UTC, JuneBridge03 requested changes
너무나도 좋은 코드 감사합니다

특히나 FeedbackThanksPage를 만들어주셔서 귀찮으심에도 너무 감사하네요 ㅠㅠ

몇 가지 리뷰 사안에 대해서 남겨드리니 한번 더 확인하고 수정해주시면 감사드릴 것 같습니다

2024-06-29 01:35 UTC, JuneBridge03 commented on frontend/src/components/feedback/staricon/StarIcon.tsx
> +export interface RatingProps {
StarIconProps가 더 좋을 것 같습니다..! (컨벤션 및 Rating 컴포넌트와의 충돌 방지)

2024-06-29 01:35 UTC, JuneBridge03 commented on frontend/src/components/feedback/staricon/StarIcon.tsx
> +const StarIcon = ({ filled }: RatingProps) => (
props로 받은 이후 컴포넌트 내에서 구조분해할당 받는 것이 좋을 듯 합니다..!

2024-06-29 01:35 UTC, JuneBridge03 commented on frontend/src/pages/FeedbackPage/FeedbackPage.tsx
> +            });
state가 없다면 두번째 인자는 생략하여도 괜찮을 듯 합니다..!

2024-06-29 01:35 UTC, JuneBridge03 commented on frontend/src/pages/FeedbackThanksPage/FeedbackThanksPage.tsx
> +export default FeedbackThanksPage;
아 맞다! 인스타 아이디도 걸면 좋을 것 같아요

2024-06-29 04:05 UTC, minseojo commented
좋은 코드 잘 보았습니다~~

2024-06-29 04:05 UTC, minseojo approved these changes

2024-07-03 03:25 UTC, JuneBridge03 approved these changes
Approve 드립니다. 반영 감사해요~

2024-07-03 03:26 UTC, merged