feat : 일기 입력 페이지 개인정보 수락 동의, 입력 페이지 검증 기능  기능 구현
software-maestro-starting-blue/daily-painting pull request #18
Opened 2024-06-28 12:21 UTC by minseojo

TSK-110, TSK 116

# [feat] 일기 입력 페이지 개인정보 수락 동의, 입력 페이지 검증 기능  기능 구현
### Pull Request 타입
- [ ] bug
- [x] feat
- [ ] style
- [ ] refactor(기능 변경 없음)
- [ ] build
- [ ] CI/CD
- [ ] doc
- [ ] chore

### TSK-110
---
- 일기 입력 페이지 개인정보 수락 동의 기능 구현
    - 체크 안하면 일기 작성 불가능 

### TSK-116
---
- 일기 입력 페이지 검증 기능 구현 추가
    - Emotion, metPerson, Weather 검증 기능
        - 최소 하나 선택
    - DiaryContent 검증 기능
        - 최소1글자, 최대 200글자

2024-06-29 01:36 UTC, JuneBridge03 requested changes
너무 좋은 코드 감사드립니다!

컴포넌트 수가 굉장히 많은 페이지여서 한번에 관리하시기 힘드셨을 텐데 그러함에도 완료해주셔서 너무 감사드립니다!

조금 더 나은 상황을 위해 여러 의견을 작성해드리니 확인해주시면 너무 감사드릴 것 같습니다!!

2024-06-29 01:36 UTC, JuneBridge03 commented on frontend/src/pages/DiaryFormPage/DiaryFormPage.tsx
>  }
type을 구체적으로 정의하여서 Request와 Response를 handling 하는 것은 굉장히 좋다고 생각합니다!

그러나, 이러한 타입을 하나의 tsx 파일 내에서 관리해야 하는지 아니면 types 폴더 내에서 관리해야 하는지에 대하여 논의할 필요성이 있어보입니다.

2024-06-29 01:36 UTC, JuneBridge03 commented on frontend/src/components/diaryform/DiaryContent/DiaryContent.tsx
>  }
isShaking을 통해서 로직을 분리한 점은 너무 좋다고 생각합니다.
그러나, content와 setContent로 setter를 그대로 넘겨주는 형태보다는 handler를 넘겨주는 형태로 가면 좋을 것 같습니다.
물론 현 상황에서는 setter를 넘겨주어도 기존에 예상한 로직대로 실행이 되나,
추후에 로직을 수정할 때 (예를 들어서 200자가 넘어가면 아예 글이 안 작성되도록) 구조를 아예 바꿔야 한다는 문제점이 발생할 수도 있을 것 같습니다..!
다음과 같이 코드를 별첨하니 참고해주시면 너무 감사드릴 것 같습니다!

'현 컴포넌트'
export interface DiaryContentProps {
content: string;
onContentChange: ChangeEventHandler<HTMLTextAreaElement>;
isShaking: boolean
}

'상위 컴포넌트'
const handleDiaryContentChange: ChangeEventHandler<HTMLTextAreaElement> = (e: ChangeEvent<HTMLTextAreaElement>) => {
setContent(e.target.value);
}

2024-06-29 01:36 UTC, JuneBridge03 commented on frontend/src/components/diaryform/MetPeopleSelectionLayout/MetPeopleSelectionLayout.tsx
> +    selectedPeople: string[];
selectedPeople보다는 isSelected: boolean으로 설정하는 것이 더 좋을 것 같습니다.

그 후 위의 mapping에서 'selectedPeople.includes(person)'을 isSelected의 인자로 넣어주는 로직으로 수정하면 될 듯 합니다.

2024-06-29 01:36 UTC, JuneBridge03 commented on frontend/src/pages/DiaryFormPage/DiaryFormPage.tsx
> +            ></PersonalInformationLayout>
통일감 있게 /> 로 처리하는 것도 좋다고 생각합니다~!

2024-06-29 01:36 UTC, JuneBridge03 commented on frontend/src/components/diaryform/SubmitButton/SubmitButton.tsx
> +    disabled: boolean;
두 상태를 적절히 나누어서 처리하는 형태는 매우 좋다고 생각합니다!

그러나, 상태를 나타내는 boolean인자의 변수명은 isLoading, isDisabled와 같이 is + (과거형)으로 작성하는 형태가 더 매력적일 듯 합니다~

2024-06-29 01:36 UTC, JuneBridge03 commented on frontend/src/pages/DiaryResultPage/DiaryResultPage.css
> +}
혹시 수정하신 이유를 알 수 있을까요? conflict의 우려가 있을 듯 합니다..!

2024-06-29 01:36 UTC, JuneBridge03 commented on frontend/src/pages/DiaryFormPage/DiaryFormPage.tsx
> +                },
현재 시점에서 논하기에는 너무 이르기는 하나, 추후에는 이러한 state에 대한 type 지정에 대한 논의도 필요해보이네요 🥲

2024-06-29 01:36 UTC, JuneBridge03 commented on frontend/src/components/diaryform/DiaryContent/DiaryContent.tsx
>      const handleDiaryContentChange = (e: ChangeEvent<HTMLTextAreaElement>) => {
개인적으로는 변수명을 event라 지정하는 것도 괜찮을 듯 합니다..!

2024-06-29 01:36 UTC, JuneBridge03 commented on frontend/src/pages/DiaryFormPage/DiaryFormPage.tsx
> +                console.error("Error fetching form data:", error);
사용자를 위해서 alert도 하면 좋을 듯 합니다!!

2024-06-29 02:04 UTC, minseojo commented on frontend/src/pages/DiaryResultPage/DiaryResultPage.css
> +}
실수인거 같습니다ㅋㅋㅋ 돌려놓겠습니다

2024-06-29 05:14 UTC, minseojo commented on frontend/src/pages/DiaryFormPage/DiaryFormPage.tsx
>  }
넵 좋습니다.

2024-06-29 05:14 UTC, minseojo commented on frontend/src/pages/DiaryFormPage/DiaryFormPage.tsx
> +                },
넵 좋습니다.

2024-06-29 05:32 UTC, minseojo commented
> 너무 좋은 코드 감사드립니다!
> 
> 컴포넌트 수가 굉장히 많은 페이지여서 한번에 관리하시기 힘드셨을 텐데 그러함에도 완료해주셔서 너무 감사드립니다!
> 
> 조금 더 나은 상황을 위해 여러 의견을 작성해드리니 확인해주시면 너무 감사드릴 것 같습니다!!

퀄리티 높은 리뷰 감사합니다. 
리뷰 내용 반영해보았는데 검토 부탁드립니다!

2024-06-29 11:26 UTC, SproutMJ requested changes

2024-06-29 11:26 UTC, SproutMJ commented on frontend/src/components/diaryform/PersonalInformationAgreementLayout/PersonalInformationAgreementLayout.tsx
> +    const { isCheckd, onClick, ...rest } = props;
isChecked 오타인 것 같습니다. 확인부탁드립니다!

2024-06-29 11:26 UTC, SproutMJ commented on frontend/src/components/diaryform/PersonalInformationAgreementLayout/PersonalInformationAgreementLayout.tsx
> +                개인 일기 저장 및 처리에 대한 동의서
"서비스 개선을 위한 이용"에 대한 부분이 명시가 되는 것도 좋을 것 같아요. 저희가 실제로 작성한 일기를 보게될 것 같기 때문입니다.

2024-06-29 11:26 UTC, SproutMJ commented on frontend/src/components/diaryform/PersonalInformationAgreementLayout/PersonalInformationAgreementLayout.tsx
> +개인 일기 저장 및 처리에 대한 동의서
"서비스 개선을 위한 이용"에 대한 부분이 이부분도 들어가면 좋을 것 같아요.

2024-06-29 11:26 UTC, SproutMJ commented on frontend/src/components/diaryform/PersonalInformationAgreementLayout/PersonalInformationAgreementLayout.tsx
> +   - 수집된 일기 내용은 사용자의 개인 기록 보관을 목적으로 사용되며, 다른 목적으로 사용되지 않습니다.
특히 이부분에서 기록 보관을 목적으로 하는 것이 아니라 보는 것에도 동의하는지에 대한 문구가 들어가면 좋을 것 같아요.

2024-06-29 11:26 UTC, SproutMJ commented on frontend/src/components/diaryform/PersonalInformationAgreementLayout/PersonalInformationAgreementLayout.tsx
> +   - 사용자가 서비스를 탈퇴하거나 정보 삭제를 요청할 경우, 수집된 모든 정보는 완전히 삭제됩니다.
저희는 서비스 탈퇴가 아직 없어서 삭제를 요청하는 경우에 대한 부분만 있으면 좋을 것 같습니다.

2024-06-29 11:26 UTC, SproutMJ commented on frontend/src/components/diaryform/PersonalInformationAgreementLayout/PersonalInformationAgreementLayout.tsx
> +   - 동의 철회는 서비스 내 설정 메뉴를 통해 쉽게 할 수 있습니다.
탈퇴와 마찬가지로 설정메뉴가 없어서 메일 등으로 요청을 해야할 것 같습니다.

2024-06-29 11:26 UTC, SproutMJ commented on frontend/src/components/diaryform/PersonalInformationAgreementLayout/PersonalInformationAgreementLayout.tsx
> +위 내용을 충분히 이해하였으며, 이에 동의합니다.
종합하면, 이런거는 어떤가요

개인 일기 저장 및 처리와 품질 개선을 위한 저장 및 활용에 대한 동의서

1. 목적
   - 본 동의서는 사용자가 작성한 일기 내용의 저장 및 처리와 품질 개선을 위한 저장 및 활용에 대한 동의와 관련된 사항을 명확히 하기 위해 작성되었습니다.

2. 수집하는 정보
   - 사용자가 작성한 일기 내용
   - 일기 작성 날짜 및 시간
   - 타인의 지식 재산권을 침해하는 내용 또는 본인이나 타인의 개인정보, 비밀정보, 사생활을 침해하는 내용을 포함하지 말아주십시오.

3. 정보의 사용
   - 수집된 일기 내용은 그림일기 생성과 품질 개선을 위한 저장 및 활용을 목적으로 사용됩니다.
   - 수집된 정보는 사용자의 요청에 따라 언제든지 삭제할 수 있습니다.

4. 정보의 보관
   - 사용자의 일기 내용은 보안이 유지되는 서버에 안전하게 저장됩니다.
   - 사용자가 정보 삭제를 요청할 경우, 수집된 모든 정보는 완전히 삭제됩니다.

5. 정보의 공유
   - 사용자의 일기 내용은 어떠한 경우에도 제3자와 공유되지 않습니다.
   - 법적 요구가 있을 경우에만 관련 법률에 따라 정보를 제공할 수 있습니다.

6. 동의 철회
   - 사용자는 언제든지 동의를 철회할 수 있으며, 동의 철회 시 일기 내용이 삭제됩니다.
   - 동의 철회는 고객 지원팀(startingblue0603@gmail.com)으로 연락 주시기 바랍니다.

7. 문의
   - 일기 내용 저장 및 처리 또는 품질 개선을 위한 저장 및 활용에 대한 문의사항은 고객 지원팀(startingblue0603@gmail.com)으로 연락 주시기 바랍니다.

위 내용을 충분히 이해하였으며, 이에 동의합니다.

2024-06-29 11:27 UTC, SproutMJ requested changes
코드리뷰 남겼습니다. 잘해주셨네요
제가 남긴 부분만 확인 부탁드립니다.

2024-06-30 05:27 UTC, minseojo commented
> 코드리뷰 남겼습니다. 잘해주셨네요 제가 남긴 부분만 확인 부탁드립니다.

좋은 코드 리뷰 감사합니다~ 반영했습니다!

2024-07-01 05:49 UTC, JuneBridge03 approved these changes
넵 좋은 것 같습니다~ 반영해주셔서 감사드립니다

2024-07-01 06:24 UTC, minseojo commented on frontend/src/components/diaryform/WeatherSelectionLayout/WeatherSelectionLayout.tsx
> +    setWeather: (weather: string) => void;
이 부분 변경이 안됐어서 다시 수정했습니다!

2024-07-01 07:43 UTC, SproutMJ approved these changes
반영 감사합니다!

2024-07-03 03:23 UTC, merged