[refactor] 커스텀 예외 추가, 도메인의 필드를 VO로 변경
software-maestro-starting-blue/daily-painting pull request #20
Opened 2024-06-29 04:13 UTC by SproutMJ

### Pull Request 타입
- [ ] bug
- [ ] feat
- [ ] style
- [x] refactor(기능 변경 없음)
- [ ] build
- [ ] CI/CD
- [ ] doc
- [ ] chore

### TSK-94
---
* 구현 내용
예외를 커스텀예외로 변경

* 추가 발생한 문제
ErrorResponse가 아직 없어 ExceptionHandler는 별도로 추가해야됨

### TSK-97
---
* 구현 내용
값객체를 이용해 검증로직을 리팩토링

* 추가 발생한 문제

2024-06-29 05:37 UTC, JuneBridge03 approved these changes
필드를 VO로 변경하는 방법이 있다니 ㄷㄷ 맛있네요

2024-06-29 05:37 UTC, JuneBridge03 commented on backend/src/main/java/com/startingblue/dailypainting/feedback/domain/Feedback.java
> +        }
해당 두 로직을 나눈 이유는 어떻게 되는 지가 궁금합니다!

2024-06-29 05:50 UTC, minseojo requested changes
VO를 추가해서 검증을 한 코드 잘 보았습니다~

exception 관련 코드에 대해서 패키지 변경 요청드립니다!!

2024-06-29 05:50 UTC, minseojo commented on backend/src/main/java/com/startingblue/dailypainting/diary/exception/DiaryNotFoundException.java
> +public final class DiaryNotFoundException extends RuntimeException {
DiaryNotFoundException이 바로 RuntimeException 을 상속 받는 것보다는

RuntimeException ◃- DiaryException ◃- DiaryNotFoundException 
이런 구조는 어떻게 생각하시나요?

2024-06-29 05:50 UTC, minseojo commented on backend/src/main/java/com/startingblue/dailypainting/diary/exception/CommentLengthOverException.java
> +package com.startingblue.dailypainting.diary.exception;
현재 exception 코드들이 diary 패키지에 있는데 feedback.exception 으로 옮겨야 할 것 같습니다!

2024-07-03 03:25 UTC, minseojo approved these changes

2024-07-03 03:30 UTC, SproutMJ commented on backend/src/main/java/com/startingblue/dailypainting/feedback/domain/Feedback.java
> +        }
이거 원래 validate에서 여러 필드를 검증하는 로직이었는데 vo로 빠지면서 validateDiary만 남게되었습니다..

2024-07-03 04:33 UTC, SproutMJ commented on backend/src/main/java/com/startingblue/dailypainting/diary/exception/DiaryNotFoundException.java
> +public final class DiaryNotFoundException extends RuntimeException {
아 넵 적용했습니다!

2024-07-03 04:38 UTC, merged