feat: 일기 작성 API 개발
software-maestro-starting-blue/daily-painting pull request #6
Opened 2024-06-19 18:50 UTC by minseojo

TSK-71

## 일기 작성 API 개발
- [GET] /api/diaries 구현
- [POST] /api/diaries  구현
- ChatGPT Serveice 구현
    - sendDiaryToChatGpt() 메서드 수정 필요
        - String requestBody = "{\"model\":\"dall-e-3\", \"prompt\":\"" + diaryContent + "\", \"n\":1, \"size\":\"1024x1024\"}";
        - 해당 내용 수정 필요. (프롬프트, 날씨, 감정, 만난 사람 반영 등)
   - sendDiaryToChatGpt() 메서드 비동기 내용 인지 및 공부 필요

2024-06-20 08:35 UTC, SproutMJ requested changes
코드 구현하신거 잘 봤습니다.
제가 남긴 의견 화인 한번 부탁드려요.

2024-06-20 08:35 UTC, SproutMJ commented on backend/src/main/java/com/startingblue/dailypainting/chatgpt/service/ChatGptService.java
> +    private String apiKey; // 실제 API 키
코드를 잘 작성하면 주석은 안쓰는 편이 좋다고 생각하는데 어떻게 생각하시나요? 일단 다른 주석에 다 코멘트를 달지 않고 여기다만 작성해봅니다.

2024-06-20 08:35 UTC, SproutMJ commented on backend/src/main/java/com/startingblue/dailypainting/chatgpt/service/ChatGptService.java
> +        HttpHeaders headers = new HttpHeaders();
final은 필수적인 요구사항은 아니지만 일단 여기다만 대표로 남겨봅니다.

2024-06-20 08:35 UTC, SproutMJ commented on backend/src/main/java/com/startingblue/dailypainting/chatgpt/service/ChatGptService.java
> +        // 프롬프트 수정이 필요함.
주석 맨 앞에 TODO: 를 넣으면 아마 ide에서 추적이 가능할겁니다. 나중에 관리하기 편해지겠죠

2024-06-20 08:35 UTC, SproutMJ commented on backend/src/main/java/com/startingblue/dailypainting/chatgpt/service/ChatGptService.java
> +            throw new RuntimeException("ChatGPT API 호출 에러");
저희가 나중에 예외가 늘어난다면 custom exception을 고려해보는 것도 좋을 것 같아요.
의견 부탁드립니다!

2024-06-20 08:35 UTC, SproutMJ commented on backend/src/main/java/com/startingblue/dailypainting/chatgpt/service/ChatGptService.java
> +        headers.set("Content-Type", "application/json");
헤더는 org.springframework.http.HttpHeaders, 뒷부분은 상수를 사용하면 매직넘버를 제거할 수 있겠네요.
사실 한군데만 사용되는 상수는 취향차이긴 한데 의견 남겨주시면 감사하겠습니다.
다른 상수 부분에는 코멘트를 달지 않고 여기에 대표로 달겠습니다.

2024-06-20 08:35 UTC, SproutMJ commented on backend/src/main/java/com/startingblue/dailypainting/chatgpt/service/ChatGptService.java
> +        throw new RuntimeException("존재하지 않는 Dall-E 3 URL 입니다.");
catch 블록에서 throw new RuntimeException("존재하지 않는 Dall-E 3 URL 입니다.");를 사용하지 않고 바깥에서 호출하는 이유가 있을까요?
1. 성공을 해도 throw new RuntimeException("존재하지 않는 Dall-E 3 URL 입니다.");가 호출됨
2. 추후에 catch에서 e.printStackTrace();만 호출되면 예외처리가 사라짐
일단 두가지 이슈가 있을 것 같네요

2024-06-20 08:35 UTC, SproutMJ commented on backend/src/main/java/com/startingblue/dailypainting/diary/controller/DiaryController.java
> +
저는 이게 비즈니스 로직(일기저장-지피티전송-이미지url저장 흐름) 같은데 어쩧게 생각하시나요? 만약 비즈니스 로직이라면 서비스 계층으로 가면 좋을 것 같아요.
그리고 주석 없어도 코드 충분히 이해 가능한 것 같습니다!

2024-06-20 08:35 UTC, SproutMJ requested changes
코드 구현하신거 잘 봤습니다.
제가 남긴 의견 화인 한번 부탁드려요.

2024-06-20 09:20 UTC, JuneBridge03 reviewed
작성해주신 코드 너무나도 잘 보았습니다.
개인적으로 보았을 때는 백엔드 로직 상에 있는 특별한 문제는 없는 것 같습니다.

이와 별개로 코멘트를 몇 개 작성하기는 하였는데요. 모든 코멘트가 나온 이유를 생각하여 보니 이는 백엔드 로직 구현에서의 문제라기 보다는 백엔드에서 OpenAI와 통신하는 과정을 담당하는 branch가 아니었는데 어느정도 담당하게 되면서(?) 생기는 문제인 것 같습니다.
곧, 이는 추가적으로 논의해야 할 문제들이어서 추후의 미팅에서 한번 이야기해보시죠!

좋은 코드 잘 보았습니다!

2024-06-20 09:20 UTC, JuneBridge03 commented on backend/src/main/java/com/startingblue/dailypainting/chatgpt/service/ChatGptService.java
> +        String requestBody = "{\"model\":\"dall-e-3\", \"prompt\":\"" + diaryContent + "\", \"n\":1, \"size\":\"1024x1024\"}";
requestBody를 제작하는 함수가 있으면 좋을 것 같습니다..!
그리고 각 변수들 (model, size 등..)을 상수로 저장한 이후에 사용하는 형태로 가는 것이 괜찮을 것 같다는 생각이 듭니다..!

2024-06-20 09:20 UTC, JuneBridge03 commented on backend/src/main/java/com/startingblue/dailypainting/chatgpt/service/ChatGptService.java
> +    public CompletableFuture<String> sendDiaryToChatGpt(String diaryContent) {
로직 구현하시느라 힘드셨을 텐데, AI 부분을 따로 빼내어서 또 구현해주셔서 너무나 감사드립니다.
다만, 다음과 같은 우려사항이 있기는 하나, 아직 프롬프트 구성을 진행하고 있어서 어쩔 수 없이 발생한 문제라고도 생각합니다.

일기의 데이터(diaryContent)를 바로 Dall-E에게 넘겨주어서 일기를 그리는 것이 아닌, 다음과 같은 프로세스로 진행됩니다.
기존 일기 -(GPT 4o)-> Json 형태의 시놉시스 -(Dall-E)-> 이미지
개인적인 생각으로는 sendDiaryToChatGpt라는 하나의 함수 내에서 위의 모든 과정을 관리하는 것은 단일책임이 아닌 것 같아서 차라리

* 기존일기를 Json 형태의 시놉시스로 만들어주는 함수
* 시놉시스를 재구성한 이후 이미지를 생성하는 함수
* 위의 두 과정을 엮는 public 함수
로 구현하는 것이 더 좋을 것 같다는 생각도 듭니다.
다만, 이렇게 구성하는 것이 옳은가?에 대한 확신은 없기에 의견을 듣고 싶습니다!


+ 이에 따라 domain 명도 chatgpt보다는 openai로 바꾸는 것이 어떤가 싶은 개인적인 의견도 있습니다...!

2024-06-20 10:15 UTC, minseojo commented on backend/src/main/java/com/startingblue/dailypainting/chatgpt/service/ChatGptService.java
> +    private String apiKey; // 실제 API 키
넵 주석을 최대한 안쓰는게 좋다고 생각합니다.

2024-06-20 10:16 UTC, minseojo commented on backend/src/main/java/com/startingblue/dailypainting/chatgpt/service/ChatGptService.java
> +        HttpHeaders headers = new HttpHeaders();
넵 까먹었네요.. 변수의 값이 변경되지 않도록 보장하고 싶을 때는 final을 사용하겠습니다.

2024-06-20 10:17 UTC, minseojo commented on backend/src/main/java/com/startingblue/dailypainting/chatgpt/service/ChatGptService.java
> +            throw new RuntimeException("ChatGPT API 호출 에러");
넵 저도 커스텀예외로 만들어서 관리하는게 좋다고 생각합니다

2024-06-20 10:17 UTC, minseojo commented on backend/src/main/java/com/startingblue/dailypainting/chatgpt/service/ChatGptService.java
> +        headers.set("Content-Type", "application/json");
넵 상수 부분 신경써보겠습니다

2024-06-20 10:22 UTC, minseojo commented on backend/src/main/java/com/startingblue/dailypainting/chatgpt/service/ChatGptService.java
> +        throw new RuntimeException("존재하지 않는 Dall-E 3 URL 입니다.");
이 부분은 제가 실수한 것 같네요.

추 후 `new RuntimeException()`을 커스텀 에러로 바꾸어서 관리하려는 목적으로 추가한 코드이기는 한데 catch블록 안에서 처리하는게 맞는것 같네요.

1번의 경우에는 성공을하면 return이 되서 throw new RuntimeException("존재하지 않는 Dall-E 3 URL 입니다.");이 호출은 되지 않습니다.

2024-06-20 10:24 UTC, minseojo commented on backend/src/main/java/com/startingblue/dailypainting/diary/controller/DiaryController.java
> +
(일기저장-지피티전송-이미지url저장 흐름) 이 부분을 하나의 트랜잭션으로 묶어서 서비스로 나누면 좋을 것 같다는 말 일까요?

넵 주석부분은 참고하겠습니다!

2024-06-20 10:25 UTC, minseojo commented on backend/src/main/java/com/startingblue/dailypainting/chatgpt/service/ChatGptService.java
> +        String requestBody = "{\"model\":\"dall-e-3\", \"prompt\":\"" + diaryContent + "\", \"n\":1, \"size\":\"1024x1024\"}";
넵 
변수들을 상수로 저장하고 `requestBody` 부분을 만드는것도 메서드로 분리하는게 좋아보입니다.

2024-06-20 10:29 UTC, minseojo commented on backend/src/main/java/com/startingblue/dailypainting/chatgpt/service/ChatGptService.java
> +    public CompletableFuture<String> sendDiaryToChatGpt(String diaryContent) {
넵 우선 큰 틀의 기능을 구현하는데 의의를 두었고, 말씀하신 부분은 추가하고, 수정해야 될 것 같습니다.


```
- 기존일기를 Json 형태의 시놉시스로 만들어주는 함수
- 시놉시스를 재구성한 이후 이미지를 생성하는 함수
위의 두 과정을 엮는 public 함수
로 구현하는 것이 더 좋을 것 같다는 생각도 듭니다.
다만, 이렇게 구성하는 것이 옳은가?에 대한 확신은 없기에 의견을 듣고 싶습니다!
```
이 부분은 OpenAiService 코드에
```
- private 기존일기를 Json 형태의 시놉시스로 만들어주는 메서드
- private 시놉시스를 재구성한 이후 이미지를 생성하는 메서드
- public 두 메서드 연결 () {
    기존일기를 Json 형태의 시놉시스로 만들어주는 메서드()
     시놉시스를 재구성한 이후 이미지를 생성하는 메서드()
}
```

이런식으로 하면 될 것 같습니다!

도메인명도 openAi가 더 좋은것 같네요

2024-06-20 15:45 UTC, SproutMJ commented on backend/src/main/java/com/startingblue/dailypainting/chatgpt/service/ChatGptService.java
> +        headers.set("Content-Type", "application/json");
영역(scope)이 어느정도인지에 따라 달라질 것 같습니다. 여러 클래스에서 사용되는 상수라면 별도의 클래스에서 관리하는 편이 좋겠지만 지금 보이는 상수들은 그정도는 아닌 것 같으니 private final 정도로 상단에 두면 좋을 것 같아요.
로깅 메시지 정도는 나중에 관리해볼 수 있겠네요.

2024-06-20 15:46 UTC, SproutMJ commented on backend/src/main/java/com/startingblue/dailypainting/chatgpt/service/ChatGptService.java
> +        throw new RuntimeException("존재하지 않는 Dall-E 3 URL 입니다.");
아 early return이 되면 상관 없겠네요

2024-06-20 15:47 UTC, SproutMJ commented on backend/src/main/java/com/startingblue/dailypainting/diary/controller/DiaryController.java
> +
서비스 계층으로 가야할 로직이지 않나 하는 의견이었습니다. 그렇게만 한다면 그에 대한 구현은 상관 없습니다.

2024-06-21 09:03 UTC, SproutMJ approved these changes
확인 했습니다. 감사합니다!

2024-06-21 09:06 UTC, JuneBridge03 approved these changes
너무나도 좋은 코드.. 감사합니다

2024-06-21 09:06 UTC, merged