[feat] 피드백 생성 페이지 구현
software-maestro-starting-blue/daily-painting pull request #8
Opened 2024-06-21 11:53 UTC by SproutMJ

# [feat] 피드백 생성 페이지 구현
### Pull Request 타입
- [ ] bug
- [x] feat
- [ ] style
- [ ] refactor(기능 변경 없음)
- [ ] build
- [ ] CI/CD
- [ ] doc
- [ ] chore

### TSK-59
---
* 구현 내용
피드백 생성 페이지 구현
별점이 0점이거나 추가 의견이 500자를 넘거나 좋아하는 캐릭터가 500자를 넘는 경우 alert이 뜨도록 구현
api 호출 시 루트 디렉토리의 .env 파일의 REACT_APP_BASE_URL를 사용하도록 구현
.gitignore에서 .env를 추적하지 않도록 수정
axios 의존성 추가

* 추가 발생한 문제

2024-06-22 04:42 UTC, JuneBridge03 requested changes
너무나 좋은 코드 작성해주셔서 감사합니다.

특히나 복잡한 페이지 구성하시느라 코드와 css 적으로 너무 고생 많으셨습니다.

코딩 컨벤션 면에서 말씀 드릴 부분이 있어서 의견을 조금 남겨드리는 바이니 참고해주시면 감사하겠습니다!

2024-06-22 04:42 UTC, JuneBridge03 commented on frontend/src/pages/FeedbackPage/FeedbackPage.tsx
> +export default function FeedbackPage(diaryId: number) {
함수 구조와 props는 코딩 컨벤션에 의거하여 다음과 같이 작성하시는 것이 더 좋을 것 같습니다!

export interface FeedbackPageProps {
   diaryId: number
}

export default FeedbackPage = (props: FeedbackPageProps) {
    const {diaryId, ...rest} = props;
    ...(추후 코드)...

2024-06-22 04:42 UTC, JuneBridge03 commented on frontend/src/pages/FeedbackPage/FeedbackPage.tsx
> +    );
컴포넌트 내의 레이아웃 단위는 나누어서 작업하시는 것이 추후 개발 확장성 면에서 좋을 듯 합니다...!

현재는 하나의 코드로 묶여있어서 코드를 해석하기가 힘들어진다는 생각입니다!

2024-06-22 04:42 UTC, JuneBridge03 commented on frontend/src/pages/FeedbackPage/FeedbackPage.tsx
> +    const handleStarClick = (setter: any, value: any) => {
함수 타입을 명시해주셔야 할 듯 합니다.!

2024-06-22 04:42 UTC, JuneBridge03 commented on frontend/src/pages/FeedbackPage/FeedbackPage.tsx
> +    const handleSubmit = async (e: any) => {
함수 타입을 명시해주셔야 할 듯 합니다.!

2024-06-22 04:42 UTC, JuneBridge03 commented on frontend/src/pages/FeedbackPage/FeedbackPage.tsx
> +    );
추가적으로 CSS 파일도 따로 분리하여서 className을 활용하여 작업하면 더 좋을 것 같다고도 생각합니다!

2024-06-22 04:42 UTC, JuneBridge03 commented on frontend/src/pages/FeedbackPage/FeedbackPage.tsx
> +    const handleSubmit = async (e: any) => {
그리고 이벤트 로직을 활용하게 된다면 any와 같은 형태는 지양해야 할 듯 합니다!

2024-06-22 04:42 UTC, JuneBridge03 commented on frontend/src/pages/FeedbackPage/FeedbackPage.tsx
> +    const handleStarClick = (setter: any, value: any) => {
그리고 이벤트 로직을 활용하게 된다면 any와 같은 형태는 지양해야 할 듯 합니다!

2024-06-22 04:42 UTC, JuneBridge03 commented on frontend/src/pages/FeedbackPage/FeedbackPage.tsx
> +        if(comment.length > 500) {
한 줄 띠어주는 것이 더 좋을 것 같습니다..!

(밑에 코드에서는 한 줄 띠어져 있어서 코드 통일성을 위해 그렇게 진행시키는 것이 좋을 듯 하다는 생각입니다!)

2024-06-22 04:42 UTC, JuneBridge03 commented on frontend/src/pages/FeedbackPage/FeedbackPage.tsx
> +    const StarIcon = ({ filled }: any) => (
함수 타입을 명시해주셔야 할 듯 합니다.!

그리고 이벤트 로직을 활용하게 된다면 any와 같은 형태는 지양해야 할 듯 합니다!

2024-06-22 07:53 UTC, minseojo approved these changes

2024-06-23 03:18 UTC, JuneBridge03 approved these changes
수고해주셔서 감사합니다!

2024-06-23 03:18 UTC, merged